version: '2.2'

networks:
    jenkins:
        driver: bridge
        
volumes:
    jenkins-data: {}
    jenkins-docker-certs: {}
    
services:
    jenkins:
        image: jenkins/jenkins:lts
        restart: unless-stopped
        ports:
        - "8080"
        - "50000"
        container_name: docker-jenkins
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
        networks:
            - jenkins
    pandoc:
        build: .
